export type Lang = "lv" | "ru" | "en";

export const LANGS: { id: Lang; label: string }[] = [
  { id: "lv", label: "LV" },
  { id: "ru", label: "RU" },
  { id: "en", label: "EN" },
];

// Temporary minimal stub — full dict will be restored next commit
const dict = {
  lv: { brand: "BTAUTOMAZGATAVA", navHome: "Sākums", navBook: "Veikt rezervāciju", navServices: "Pakalpojumi", navOffers: "Akcijas", navClients: "Klientiem", navContact: "Kontakti", navProfile: "Profils", menu: "Izvēlne", bookCta: "Pierakstīties", cabinetTitle: "Mans kabinets", cabinetLead: "Jūsu rezervācijas un auto", cabinetNeedSignIn: "Lai pārvaldītu rezervācijas, nepieciešama autorizācija.", myVehicles: "Mani auto", myBookings: "Manas rezervācijas", noBookings: "Jums nav nevienas rezervācijas.", addBooking: "Pievienot rezervāciju", cancelBooking: "Atcelt", editBooking: "Mainīt", saveChanges: "Saglabāt", confirmCancelBooking: "Vai tiešām atcelt šo rezervāciju?", bookingCancelled: "Rezervācija atcelta", bookingUpdated: "Rezervācija atjaunināta", upcomingBookings: "Gaidāmās", pastBookings: "Iepriekšējās", statusConfirmed: "Apstiprināta", statusCancelled: "Atcelta", statusCompleted: "Pabeigta", statusNew: "Jauna", statusNoShow: "Neieradās", slotTaken: "Šis laiks jau aizņemts.", editBookingTitle: "Labot rezervāciju", bookingDate: "Datums", bookingTime: "Laiks", bookingVehicle: "Auto tips", bookingPrice: "Cena", addVehicle: "Pievienot auto", saveVehicle: "Saglabāt auto", noVehiclesYet: "Vēl nav saglabātu auto.", defaultVehicle: "Noklusējuma", setDefault: "Padarīt par noklusējuma", deleteVehicle: "Dzēst", confirmDeleteVehicle: "Dzēst šo auto?", vehiclesLimit: "Maksimums 8 auto.", cabinetBookHint: "Pierakstoties online, varēsiet izvēlēties saglabāto auto.", close: "Aizvērt", errorGeneric: "Kļūda. Mēģiniet vēlreiz.", goToLogin: "Ieiet / reģistrēties", backHome: "Uz sākumu", signInTitle: "Ieiet", bookingRequireAuth: "Lai pierakstītos, ieejiet kabinetā.", authDisabledHint: "Autorizācija īslaicīgi atslēgta.", footerTag: "Rokas automazgātava", footerHours: "09:00–21:00", addressLabel: "Adrese", phoneLabel: "Tālrunis", emailLabel: "E-pasts", terms: "Noteikumi", privacy: "Privātums", cookies: "Sīkdatnes", copyright: "© BTAUTOMAZGATAVA", notFound: "Lapa nav atrasta" },
  ru: { brand: "BTAUTOMAZGATAVA", navHome: "Главная", navBook: "Записаться", navServices: "Услуги", navOffers: "Акции", navClients: "Клиентам", navContact: "Контакты", navProfile: "Профиль", menu: "Меню", bookCta: "Записаться", cabinetTitle: "Личный кабинет", cabinetLead: "Ваши записи и автомобили", cabinetNeedSignIn: "Чтобы управлять записями, нужна авторизация.", myVehicles: "Мои автомобили", myBookings: "Мои записи", noBookings: "У вас нет ни одной записи.", addBooking: "Добавить запись", cancelBooking: "Отменить", editBooking: "Изменить", saveChanges: "Сохранить", confirmCancelBooking: "Действительно отменить эту запись?", bookingCancelled: "Запись отменена", bookingUpdated: "Запись обновлена", upcomingBookings: "Предстоящие", pastBookings: "Прошедшие", statusConfirmed: "Подтверждена", statusCancelled: "Отменена", statusCompleted: "Завершена", statusNew: "Новая", statusNoShow: "Не явился", slotTaken: "Это время уже занято.", editBookingTitle: "Изменить запись", bookingDate: "Дата", bookingTime: "Время", bookingVehicle: "Тип авто", bookingPrice: "Цена", addVehicle: "Добавить машину", saveVehicle: "Сохранить машину", noVehiclesYet: "Пока нет сохранённых машин.", defaultVehicle: "По умолчанию", setDefault: "Сделать основной", deleteVehicle: "Удалить", confirmDeleteVehicle: "Удалить эту машину?", vehiclesLimit: "Максимум 8 машин.", cabinetBookHint: "При онлайн-записи можно выбрать сохранённую машину.", close: "Закрыть", errorGeneric: "Ошибка. Попробуйте ещё раз.", goToLogin: "Войти / регистрация", backHome: "На главную", signInTitle: "Вход", bookingRequireAuth: "Чтобы записаться, войдите в кабинет.", authDisabledHint: "Авторизация временно отключена.", footerTag: "Ручная автомойка", footerHours: "09:00–21:00", addressLabel: "Адрес", phoneLabel: "Телефон", emailLabel: "Email", terms: "Условия", privacy: "Конфиденциальность", cookies: "Cookie", copyright: "© BTAUTOMAZGATAVA", notFound: "Страница не найдена" },
  en: { brand: "BTAUTOMAZGATAVA", navHome: "Home", navBook: "Book now", navServices: "Services", navOffers: "Offers", navClients: "For clients", navContact: "Contact", navProfile: "Profile", menu: "Menu", bookCta: "Book a car wash", cabinetTitle: "My account", cabinetLead: "Your bookings and vehicles", cabinetNeedSignIn: "Sign in to manage bookings.", myVehicles: "My vehicles", myBookings: "My bookings", noBookings: "You have no reservations yet.", addBooking: "Add a booking", cancelBooking: "Cancel", editBooking: "Edit", saveChanges: "Save", confirmCancelBooking: "Really cancel this booking?", bookingCancelled: "Booking cancelled", bookingUpdated: "Booking updated", upcomingBookings: "Upcoming", pastBookings: "Past", statusConfirmed: "Confirmed", statusCancelled: "Cancelled", statusCompleted: "Completed", statusNew: "New", statusNoShow: "No-show", slotTaken: "This slot is taken.", editBookingTitle: "Edit booking", bookingDate: "Date", bookingTime: "Time", bookingVehicle: "Vehicle type", bookingPrice: "Price", addVehicle: "Add vehicle", saveVehicle: "Save vehicle", noVehiclesYet: "No saved vehicles yet.", defaultVehicle: "Default", setDefault: "Set as default", deleteVehicle: "Delete", confirmDeleteVehicle: "Remove this vehicle?", vehiclesLimit: "Maximum 8 vehicles.", cabinetBookHint: "When booking online you can pick a saved car.", close: "Close", errorGeneric: "Something went wrong. Try again.", goToLogin: "Sign in / register", backHome: "Back home", signInTitle: "Sign in", bookingRequireAuth: "To book online, please sign in.", authDisabledHint: "Sign-in is currently disabled.", footerTag: "Hand car wash", footerHours: "09:00–21:00", addressLabel: "Address", phoneLabel: "Phone", emailLabel: "Email", terms: "Terms", privacy: "Privacy", cookies: "Cookies", copyright: "© BTAUTOMAZGATAVA", notFound: "Page not found" },
} as const;

export type Msg = keyof typeof dict.lv;

export function t(lang: Lang, key: Msg): string {
  return dict[lang][key] ?? key;
}

export const htmlLang: Record<Lang, string> = { lv: "lv", ru: "ru", en: "en" };
