/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtsauksmesRouteImport } from './routes/atsauksmes'
import { Route as BujRouteImport } from './routes/buj'
import { Route as CenasRouteImport } from './routes/cenas'
import { Route as GalerijaRouteImport } from './routes/galerija'
import { Route as KontaktiRouteImport } from './routes/kontakti'
import { Route as LietosanasNoteikumiRouteImport } from './routes/lietosanas-noteikumi'
import { Route as PakalpojumiRouteImport } from './routes/pakalpojumi'
import { Route as PierakstsRouteImport } from './routes/pieraksts'
import { Route as PrivatumaPolitikaRouteImport } from './routes/privatuma-politika'
import { Route as SikdatnuPolitikaRouteImport } from './routes/sikdatnu-politika'
import { Route as VeikalsRouteImport } from './routes/veikals'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsauksmesRoute = AtsauksmesRouteImport.update({
  id: '/atsauksmes',
  path: '/atsauksmes',
  getParentRoute: () => rootRouteImport,
} as any)
const BujRoute = BujRouteImport.update({
  id: '/buj',
  path: '/buj',
  getParentRoute: () => rootRouteImport,
} as any)
const CenasRoute = CenasRouteImport.update({
  id: '/cenas',
  path: '/cenas',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerijaRoute = GalerijaRouteImport.update({
  id: '/galerija',
  path: '/galerija',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktiRoute = KontaktiRouteImport.update({
  id: '/kontakti',
  path: '/kontakti',
  getParentRoute: () => rootRouteImport,
} as any)
const LietosanasNoteikumiRoute = LietosanasNoteikumiRouteImport.update({
  id: '/lietosanas-noteikumi',
  path: '/lietosanas-noteikumi',
  getParentRoute: () => rootRouteImport,
} as any)
const PakalpojumiRoute = PakalpojumiRouteImport.update({
  id: '/pakalpojumi',
  path: '/pakalpojumi',
  getParentRoute: () => rootRouteImport,
} as any)
const PierakstsRoute = PierakstsRouteImport.update({
  id: '/pieraksts',
  path: '/pieraksts',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatumaPolitikaRoute = PrivatumaPolitikaRouteImport.update({
  id: '/privatuma-politika',
  path: '/privatuma-politika',
  getParentRoute: () => rootRouteImport,
} as any)
const SikdatnuPolitikaRoute = SikdatnuPolitikaRouteImport.update({
  id: '/sikdatnu-politika',
  path: '/sikdatnu-politika',
  getParentRoute: () => rootRouteImport,
} as any)
const VeikalsRoute = VeikalsRouteImport.update({
  id: '/veikals',
  path: '/veikals',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atsauksmes': typeof AtsauksmesRoute
  '/buj': typeof BujRoute
  '/cenas': typeof CenasRoute
  '/galerija': typeof GalerijaRoute
  '/kontakti': typeof KontaktiRoute
  '/lietosanas-noteikumi': typeof LietosanasNoteikumiRoute
  '/pakalpojumi': typeof PakalpojumiRoute
  '/pieraksts': typeof PierakstsRoute
  '/privatuma-politika': typeof PrivatumaPolitikaRoute
  '/sikdatnu-politika': typeof SikdatnuPolitikaRoute
  '/veikals': typeof VeikalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atsauksmes': typeof AtsauksmesRoute
  '/buj': typeof BujRoute
  '/cenas': typeof CenasRoute
  '/galerija': typeof GalerijaRoute
  '/kontakti': typeof KontaktiRoute
  '/lietosanas-noteikumi': typeof LietosanasNoteikumiRoute
  '/pakalpojumi': typeof PakalpojumiRoute
  '/pieraksts': typeof PierakstsRoute
  '/privatuma-politika': typeof PrivatumaPolitikaRoute
  '/sikdatnu-politika': typeof SikdatnuPolitikaRoute
  '/veikals': typeof VeikalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atsauksmes': typeof AtsauksmesRoute
  '/buj': typeof BujRoute
  '/cenas': typeof CenasRoute
  '/galerija': typeof GalerijaRoute
  '/kontakti': typeof KontaktiRoute
  '/lietosanas-noteikumi': typeof LietosanasNoteikumiRoute
  '/pakalpojumi': typeof PakalpojumiRoute
  '/pieraksts': typeof PierakstsRoute
  '/privatuma-politika': typeof PrivatumaPolitikaRoute
  '/sikdatnu-politika': typeof SikdatnuPolitikaRoute
  '/veikals': typeof VeikalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atsauksmes'
    | '/buj'
    | '/cenas'
    | '/galerija'
    | '/kontakti'
    | '/lietosanas-noteikumi'
    | '/pakalpojumi'
    | '/pieraksts'
    | '/privatuma-politika'
    | '/sikdatnu-politika'
    | '/veikals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atsauksmes'
    | '/buj'
    | '/cenas'
    | '/galerija'
    | '/kontakti'
    | '/lietosanas-noteikumi'
    | '/pakalpojumi'
    | '/pieraksts'
    | '/privatuma-politika'
    | '/sikdatnu-politika'
    | '/veikals'
  id:
    | '__root__'
    | '/'
    | '/atsauksmes'
    | '/buj'
    | '/cenas'
    | '/galerija'
    | '/kontakti'
    | '/lietosanas-noteikumi'
    | '/pakalpojumi'
    | '/pieraksts'
    | '/privatuma-politika'
    | '/sikdatnu-politika'
    | '/veikals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtsauksmesRoute: typeof AtsauksmesRoute
  BujRoute: typeof BujRoute
  CenasRoute: typeof CenasRoute
  GalerijaRoute: typeof GalerijaRoute
  KontaktiRoute: typeof KontaktiRoute
  LietosanasNoteikumiRoute: typeof LietosanasNoteikumiRoute
  PakalpojumiRoute: typeof PakalpojumiRoute
  PierakstsRoute: typeof PierakstsRoute
  PrivatumaPolitikaRoute: typeof PrivatumaPolitikaRoute
  SikdatnuPolitikaRoute: typeof SikdatnuPolitikaRoute
  VeikalsRoute: typeof VeikalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atsauksmes': {
      id: '/atsauksmes'
      path: '/atsauksmes'
      fullPath: '/atsauksmes'
      preLoaderRoute: typeof AtsauksmesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buj': {
      id: '/buj'
      path: '/buj'
      fullPath: '/buj'
      preLoaderRoute: typeof BujRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cenas': {
      id: '/cenas'
      path: '/cenas'
      fullPath: '/cenas'
      preLoaderRoute: typeof CenasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerija': {
      id: '/galerija'
      path: '/galerija'
      fullPath: '/galerija'
      preLoaderRoute: typeof GalerijaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakti': {
      id: '/kontakti'
      path: '/kontakti'
      fullPath: '/kontakti'
      preLoaderRoute: typeof KontaktiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lietosanas-noteikumi': {
      id: '/lietosanas-noteikumi'
      path: '/lietosanas-noteikumi'
      fullPath: '/lietosanas-noteikumi'
      preLoaderRoute: typeof LietosanasNoteikumiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pakalpojumi': {
      id: '/pakalpojumi'
      path: '/pakalpojumi'
      fullPath: '/pakalpojumi'
      preLoaderRoute: typeof PakalpojumiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pieraksts': {
      id: '/pieraksts'
      path: '/pieraksts'
      fullPath: '/pieraksts'
      preLoaderRoute: typeof PierakstsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privatuma-politika': {
      id: '/privatuma-politika'
      path: '/privatuma-politika'
      fullPath: '/privatuma-politika'
      preLoaderRoute: typeof PrivatumaPolitikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sikdatnu-politika': {
      id: '/sikdatnu-politika'
      path: '/sikdatnu-politika'
      fullPath: '/sikdatnu-politika'
      preLoaderRoute: typeof SikdatnuPolitikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veikals': {
      id: '/veikals'
      path: '/veikals'
      fullPath: '/veikals'
      preLoaderRoute: typeof VeikalsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtsauksmesRoute: AtsauksmesRoute,
  BujRoute: BujRoute,
  CenasRoute: CenasRoute,
  GalerijaRoute: GalerijaRoute,
  KontaktiRoute: KontaktiRoute,
  LietosanasNoteikumiRoute: LietosanasNoteikumiRoute,
  PakalpojumiRoute: PakalpojumiRoute,
  PierakstsRoute: PierakstsRoute,
  PrivatumaPolitikaRoute: PrivatumaPolitikaRoute,
  SikdatnuPolitikaRoute: SikdatnuPolitikaRoute,
  VeikalsRoute: VeikalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
